## User settings for data files and gene label

# =============================================================================
# Multiple Genes
# =============================================================================

#GENES: Primate_ACE2,Primate_TP53,Primate_BTG1,Primate_REM2

GENES: Placentals_ZNF805

#GENES: Mammalia_C11orf54,Mammalia_C18orf63,Mammalia_ERICH3,Mammalia_SMIM20,Mammalia_TMEM161B


# DEBUG
#GENES: Primate_ACE2,Primate_TP53
#GENES: Primate_ACE2

