## User settings for data files and gene label

# =============================================================================
# Multiple Genes
# =============================================================================

# Edit the 'GENES' variable below,
#     these should be the names of folders in the 'data' directory

GENES: Primate_ACE2,Primate_TP53,Primate_BTG1,Primate_REM2



# End of file
