name: AOC
channels:
  - conda-forge
  - bioconda
  - defaults
  
dependencies:
  - snakemake=7.32.4
  - hyphy=2.5.61
  - iqtree=2.1.2
  - tn93=1.0.14
  - altair=5.2.0
  - altair_saver=0.5.0
  - biopython=1.83
  - mafft=7.520
  - python=3.11.0
  - ete3=3.1.2
  - macse=2.07
  - statsmodels=0.14.2
  - vl-convert-python=1.6.1
  - networkx=3.3
  - matplotlib=3.9.2
