name: AOC CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: aoc
        environment-file: config/environment.yml
        auto-activate-base: false

    - name: Test Snakemake dry-run
      shell: bash -l {0}
      run: |
        snakemake --cores 1 --use-conda --dry-run

